### ISSUE TITLE
requesting a way to send "custom" parameters

### ISSUE THREAD

**Issue by stoopdapoop** [wesleythorsen1/dotnet-craigslist#13]
I'm interested in setting the "purveyor" parameter to a value so that I can search by owner. There doesn't appear to be a way to add this parameter without modifying the library. it would be nice if we could supply a dictionary of parameters to a search request or posting request.

**Comment by wesleythorsen1** [comment]
Looks like craigslist has updated the way they list "By Owner" and "By Dealer" with the purveyor query parameter. I will update.
In the meantime you can add the purveyor parameter with:
```
var request = new SearchRequest(...);
request.SetParameter("purveyor", "owner");
//or
request.SetParameter("purveyor", "dealer");
```

Also, if you'd like to pass a dictionary of parameters to the search request you can use the following constructor:
https://github.com/wesleythorsen1/dotnet-craigslist/blob/b4c47d3d1b7921cd64f3ad98f7bcabf5fb3795d9/src/DotnetCraigslist/Requests/SearchRequest.Base.cs#L63

**Comment by stoopdapoop** [comment]
Awesome, thanks Wesley, this is what I was hoping for, I don't know why I didn't see these methods...

**Comment by wesleythorsen** [comment]
Purveyor has been added in version `0.4.0`.
